### ISSUE TITLE
How do I get set up

### ISSUE THREAD

**Issue by ignorant96** [sciope/sciope#8]
Hello, I tried to get the documents about how to set up sciope, but the link 'Documentation' in 'How do I get set up' part did not work.It showed Error 404 saying 'There is not a Github pages site here'. So, I want to know if there is something wrong about the link of documentation and how to get the documents about sciope.Thank You!

**Comment by Wrede** [comment]
Thanks @ignorant96! Since we change our organization we have had some broken links. Should be fixed now!
